name: Codacy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]   # (2) matriz de versiones

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install helper tools (jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Parchea pins problemáticos sin tocar el repo (networkx==3.5 no existe en PyPI)
      - name: Patch known bad pins in requirements
        run: |
          if [ -f requirements.txt ] && grep -q '^networkx==3\.5$' requirements.txt; then
            sed -i 's/^networkx==3\.5$/networkx==3.4.2/' requirements.txt
            echo "Patched: networkx==3.5 -> networkx==3.4.2"
          fi
          python -m pip index versions networkx || true

      - name: Upgrade pip & tooling
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install coverage pytest pip-audit

      # ⚠️ Rosemary (editable) SOLO en 3.12 porque requiere Python >=3.12
      - name: Install project dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ "${{ matrix.python-version }}" = "3.12" ]; then
            if [ -f pyproject.toml ] || [ -f setup.py ]; then pip install -e .; fi
          else
            echo "Saltando 'pip install -e .' (rosemary requiere Python >= 3.12)"
          fi

      # (1) Verificar dependencias desactualizadas (no falla el job; pon FAIL_ON_OUTDATED=true si quieres que falle)
      - name: Check outdated dependencies
        env:
          FAIL_ON_OUTDATED: "false"
        run: |
          pip list --outdated --format=json | tee outdated.json
          COUNT=$(jq 'length' outdated.json)
          echo "Outdated packages: $COUNT"
          if [ "$COUNT" -gt 0 ]; then
            jq -r '.[:20][] | "* \(.name) \(.version) -> \(.latest_version)"' outdated.json
            if [ "$FAIL_ON_OUTDATED" = "true" ]; then
              echo "::error title=Dependencias desactualizadas::Se detectaron $COUNT paquetes desactualizados."
              exit 1
            fi
          fi

      # (3) Análisis de seguridad con pip-audit (deja informe y no corta; usa --strict si quieres que falle)
      - name: Security audit (pip-audit)
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt --format json -o pip-audit.json || true
          else
            pip-audit --format json -o pip-audit.json || true
          fi
          echo "Resumen de vulnerabilidades:"
          (jq -r '.[] | "- " + .name + " " + .version + " → " + ([.vulns[].id] | join(", "))' pip-audit.json) || echo "Sin datos"

      - name: Upload coverage to Codacy
        env:
          FLASK_ENV: testing
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_TEST_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          pip install codacy-coverage
          coverage run -m pytest app/modules/ --ignore-glob='*selenium*'
          coverage xml
          python-codacy-coverage -r coverage.xml

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-py${{ matrix.python-version }}
          path: |
            outdated.json
            pip-audit.json
            coverage.xml
